name: Deploy Bicep template

on:
  workflow_dispatch: # kjør manuelt

env:
  RESOURCE-GROUP: rg-eshoponweb-gh
  LOCATION: westeurope
  TEMPLATE-FILE: infra/simple-windows-vm.bicep

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group and deploy bicep
        uses: azure/cli@v2
        with:
          inlineScript: |

            az deployment group create \
              --resource-group $RESOURCE-GROUP \
              --template-file $TEMPLATE-FILE
